name: Publish to GitHub Pages
on:
  workflow_dispatch:


concurrency:
  group: github-pages
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/netbeheer-nederland/env-data-modeling:latest
      ports:
        - 8080
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v3
      - name: Generate site
        run: |
          git config --global --add safe.directory /__w/docs-new/docs-new
          antora --fetch antora-playbook.yml
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
